category = Category.create(name:'レディース')
children = category.children.create(name:'トップス')
children.children.create(name:'Tシャツ/カットソー(半袖/袖なし)')
children.children.create(name:'Tシャツ/カットソー(七分/長袖)')
children.children.create(name:'シャツ/ブラウス(半袖/袖なし)')
children.children.create(name:'シャツ/ブラウス(七分/長袖)')
children.children.create(name:'ポロシャツ')
children.children.create(name:'キャミソール')
children.children.create(name:'タンクトップ')
children.children.create(name:'ホルターネック')
children.children.create(name:'ニット/セーター')
children.children.create(name:'チュニック')
children.children.create(name:'カーディガン/ボレロ')
children.children.create(name:'アンサンブル')
children.children.create(name:'ベスト/ジレ')
children.children.create(name:'パーカー')
children = category.children.create(name:'ジャケット/アウター')
children.children.create(name:'テーラードジャケット')
children.children.create(name:'ノーカラージャケット')
children.children.create(name:'Gジャン/デニムジャケット')
children.children.create(name:'レザージャケット')
children.children.create(name:'ダウンジャケット')
children.children.create(name:'ライダースジャケット')
children.children.create(name:'ミリタリージャケット')
children.children.create(name:'ダウンベスト')
children.children.create(name:'ジャンパー/ブルゾン')
children.children.create(name:'ポンチョ')
children.children.create(name:'ロングコート')
children.children.create(name:'トレンチコート')
children.children.create(name:'ダッフルコート')
children.children.create(name:'ピーコート')
children = category.children.create(name:'パンツ')
children.children.create(name:'デニム/ジーンズ')
children.children.create(name:'ショートパンツ')
children.children.create(name:'カジュアルパンツ')
children.children.create(name:'ハーフパンツ')
children.children.create(name:'チノパン')
children.children.create(name:'ワークパンツ/カーゴパンツ')
children.children.create(name:'クロップドパンツ')
children.children.create(name:'サロペット/オーバーオール')
children.children.create(name:'オールインワン')
children.children.create(name:'サルエルパンツ')
children.children.create(name:'ガウチョパンツ')
children.children.create(name:'その他')
children = category.children.create(name:'スカート')
children.children.create(name:'ミニスカート')
children.children.create(name:'ひざ丈スカート')
children.children.create(name:'ロングスカート')
children.children.create(name:'キュロット')
children.children.create(name:'その他')
children = category.children.create(name:'ワンピース')
children.children.create(name:'ミニワンピース')
children.children.create(name:'ひざ丈ワンピース')
children.children.create(name:'ロングワンピース')
children.children.create(name:'その他')
children = category.children.create(name:'靴')
children.children.create(name:'ハイヒール/パンプス')
children.children.create(name:'ブーツ')
children.children.create(name:'サンダル')
children.children.create(name:'スニーカー')
children.children.create(name:'ミュール')
children.children.create(name:'モカシン')
children.children.create(name:'ローファー/革靴')
children.children.create(name:'フラットシューズ/バレエシューズ')
children.children.create(name:'長靴/レインシューズ')
children.children.create(name:'その他')
children = category.children.create(name:'ルームウェア/パジャマ')
children.children.create(name:'パジャマ')
children.children.create(name:'ルームウェア')
children.children.create(name:'レッグウェア')
children.children.create(name:'ソックス')
children.children.create(name:'スパッツ/レギンス')
children.children.create(name:'ストッキング/タイツ')
children.children.create(name:'レッグウォーマー')
children.children.create(name:'その他')
children = category.children.create(name:'帽子')
children.children.create(name:'ニットキャップ/ビーニー')
children.children.create(name:'ハット')
children.children.create(name:'ハンチング/ベレー帽')
children.children.create(name:'キャップ')
children.children.create(name:'キャスケット')
children.children.create(name:'麦わら帽子')
children.children.create(name:'その他')
children = category.children.create(name:'バッグ')
children.children.create(name:'ハンドバッグ')
children.children.create(name:'トートバッグ')
children.children.create(name:'エコバッグ')
children.children.create(name:'リュック/バックパック')
children.children.create(name:'ボストンバッグ')
children.children.create(name:'スポーツバッグ')
children.children.create(name:'ショルダーバッグ')
children.children.create(name:'クラッチバッグ')
children.children.create(name:'ポーチ/バニティ')
children.children.create(name:'ボディバッグ/ウェストバッグ')
children.children.create(name:'マザーズバッグ')
children.children.create(name:'メッセンジャーバッグ')
children.children.create(name:'ビジネスバッグ')
children.children.create(name:'旅行用バッグ/キャリーバッグ')
children = category.children.create(name:'アクセサリー')
children.children.create(name:'ネックレス')
children.children.create(name:'ブレスレット')
children.children.create(name:'バングル/リストバンド')
children.children.create(name:'リング')
children.children.create(name:'ピアス(片耳用)')
children.children.create(name:'ピアス(両耳用)')
children.children.create(name:'イヤリング')
children.children.create(name:'アンクレット')
children.children.create(name:'ブローチ/コサージュ')
children.children.create(name:'チャーム')
children.children.create(name:'その他')
children = category.children.create(name:'ヘアアクセサリー')
children.children.create(name:'ヘアゴム/シュシュ')
children.children.create(name:'ヘアバンド/カチューシャ')
children.children.create(name:'ヘアピン')
children.children.create(name:'その他')
children = category.children.create(name:'小物')
children.children.create(name:'長財布')
children.children.create(name:'折り財布')
children.children.create(name:'コインケース/小銭入れ')
children.children.create(name:'名刺入れ/定期入れ')
children.children.create(name:'キーケース')
children.children.create(name:'キーホルダー')
children.children.create(name:'手袋/アームカバー')
children.children.create(name:'ハンカチ')
children.children.create(name:'ベルト')
children.children.create(name:'マフラー/ショール')
children.children.create(name:'ストール/スヌード')
children.children.create(name:'バンダナ/スカーフ')
children.children.create(name:'ネックウォーマー')
children.children.create(name:'サスペンダー')
children = category.children.create(name:'時計')
children.children.create(name:'腕時計(アナログ)')
children.children.create(name:'腕時計(デジタル)')
children.children.create(name:'ラバーベルト')
children.children.create(name:'レザーベルト')
children.children.create(name:'金属ベルト')
children.children.create(name:'その他')
category = Category.create(name:'メンズ')
children = category.children.create(name:'トップス')
children.children.create(name:'Tシャツ/カットソー(半袖/袖なし)')
children.children.create(name:'Tシャツ/カットソー(七分/長袖)')
children.children.create(name:'シャツ')
children.children.create(name:'ポロシャツ')
children.children.create(name:'タンクトップ')
children.children.create(name:'ニット/セーター')
children.children.create(name:'パーカー')
children.children.create(name:'カーディガン')
children.children.create(name:'スウェット')
children.children.create(name:'ジャージ')
children.children.create(name:'ベスト')
children.children.create(name:'その他')
children = category.children.create(name:'ジャケット/アウター')
children.children.create(name:'テーラードジャケット')
children.children.create(name:'ノーカラージャケット')
children.children.create(name:'Gジャン/デニムジャケット')
children.children.create(name:'レザージャケット')
children.children.create(name:'ダウンジャケット')
children.children.create(name:'ライダースジャケット')
children.children.create(name:'ミリタリージャケット')
children.children.create(name:'ナイロンジャケット')
children.children.create(name:'フライトジャケット')
children.children.create(name:'ダッフルコート')
children.children.create(name:'ピーコート')
children.children.create(name:'ステンカラーコート')
children.children.create(name:'トレンチコート')
children.children.create(name:'モッズコート')
children = category.children.create(name:'パンツ')
children.children.create(name:'デニム/ジーンズ')
children.children.create(name:'ワークパンツ/カーゴパンツ')
children.children.create(name:'スラックス')
children.children.create(name:'チノパン')
children.children.create(name:'ショートパンツ')
children.children.create(name:'ペインターパンツ')
children.children.create(name:'サルエルパンツ')
children.children.create(name:'オーバーオール')
children.children.create(name:'その他')
children = category.children.create(name:'靴')
children.children.create(name:'スニーカー')
children.children.create(name:'サンダル')
children.children.create(name:'ブーツ')
children.children.create(name:'モカシン')
children.children.create(name:'ドレス/ビジネス')
children.children.create(name:'長靴/レインシューズ')
children.children.create(name:'デッキシューズ')
children.children.create(name:'その他')
children = category.children.create(name:'バッグ')
children.children.create(name:'ショルダーバッグ')
children.children.create(name:'トートバッグ')
children.children.create(name:'ボストンバッグ')
children.children.create(name:'リュック/バックパック')
children.children.create(name:'ウエストポーチ')
children.children.create(name:'ボディーバッグ')
children.children.create(name:'ドラムバッグ')
children.children.create(name:'ビジネスバッグ')
children.children.create(name:'トラベルバッグ')
children.children.create(name:'メッセンジャーバッグ')
children.children.create(name:'エコバッグ')
children.children.create(name:'その他')
children = category.children.create(name:'スーツ')
children.children.create(name:'スーツジャケット')
children.children.create(name:'スーツベスト')
children.children.create(name:'スラックス')
children.children.create(name:'セットアップ')
children.children.create(name:'その他')
children = category.children.create(name:'帽子')
children.children.create(name:'キャップ')
children.children.create(name:'ハット')
children.children.create(name:'ニットキャップ/ビーニー')
children.children.create(name:'ハンチング/ベレー帽')
children.children.create(name:'キャスケット')
children.children.create(name:'サンバイザー')
children.children.create(name:'その他')
children = category.children.create(name:'アクセサリー')
children.children.create(name:'ネックレス')
children.children.create(name:'ブレスレット')
children.children.create(name:'バングル/リストバンド')
children.children.create(name:'リング')
children.children.create(name:'ピアス(片耳用)')
children.children.create(name:'ピアス(両耳用)')
children.children.create(name:'アンクレット')
children.children.create(name:'その他')
children = category.children.create(name:'小物')
children.children.create(name:'長財布')
children.children.create(name:'折り財布')
children.children.create(name:'マネークリップ')
children.children.create(name:'コインケース/小銭入れ')
children.children.create(name:'名刺入れ/定期入れ')
children.children.create(name:'キーケース')
children.children.create(name:'キーホルダー')
children.children.create(name:'ネクタイ')
children.children.create(name:'手袋')
children.children.create(name:'ハンカチ')
children.children.create(name:'ベルト')
children.children.create(name:'マフラー')
children.children.create(name:'ストール')
children.children.create(name:'バンダナ')
children = category.children.create(name:'時計')
children.children.create(name:'腕時計(アナログ)')
children.children.create(name:'腕時計(デジタル)')
children.children.create(name:'ラバーベルト')
children.children.create(name:'レザーベルト')
children.children.create(name:'金属ベルト')
children.children.create(name:'その他')
children = category.children.create(name:'水着')
children.children.create(name:'一般水着')
children.children.create(name:'スポーツ用')
children.children.create(name:'アクセサリー')
children.children.create(name:'その他')
children = category.children.create(name:'レッグウェア')
children.children.create(name:'ソックス')
children.children.create(name:'レギンス/スパッツ')
children.children.create(name:'レッグウォーマー')
children.children.create(name:'その他')
children = category.children.create(name:'アンダーウェア')
children.children.create(name:'トランクス')
children.children.create(name:'ボクサーパンツ')
children.children.create(name:'その他')
children = category.children.create(name:'その他')
category = Category.create(name:'ベビー・キッズ')
children = category.children.create(name:'ベビー服(女の子用) ~95cm')
children.children.create(name:'トップス')
children.children.create(name:'アウター')
children.children.create(name:'パンツ')
children.children.create(name:'スカート')
children.children.create(name:'ワンピース')
children.children.create(name:'ベビードレス')
children.children.create(name:'おくるみ')
children.children.create(name:'下着/肌着')
children.children.create(name:'パジャマ')
children.children.create(name:'ロンパース')
children.children.create(name:'その他')
children = category.children.create(name:'ベビー服(男の子用) ~95cm')
children.children.create(name:'トップス')
children.children.create(name:'アウター')
children.children.create(name:'パンツ')
children.children.create(name:'おくるみ')
children.children.create(name:'下着/肌着')
children.children.create(name:'パジャマ')
children.children.create(name:'ロンパース')
children.children.create(name:'その他')
children = category.children.create(name:'ベビー服(男女兼用) ~95cm')
children.children.create(name:'トップス')
children.children.create(name:'アウター')
children.children.create(name:'パンツ')
children.children.create(name:'おくるみ')
children.children.create(name:'下着/肌着')
children.children.create(name:'パジャマ')
children.children.create(name:'ロンパース')
children.children.create(name:'その他')
children = category.children.create(name:'キッズ服(女の子用) 100cm~')
children.children.create(name:'コート')
children.children.create(name:'ジャケット/上着')
children.children.create(name:'トップス(Tシャツ/カットソー)')
children.children.create(name:'トップス(トレーナー)')
children.children.create(name:'トップス(チュニック)')
children.children.create(name:'トップス(タンクトップ)')
children.children.create(name:'トップス(その他)')
children.children.create(name:'スカート')
children.children.create(name:'パンツ')
children.children.create(name:'ワンピース')
children.children.create(name:'セットアップ')
children.children.create(name:'パジャマ')
children.children.create(name:'フォーマル/ドレス')
children.children.create(name:'和服')
children = category.children.create(name:'キッズ服(男の子用) 100cm~')
children.children.create(name:'コート')
children.children.create(name:'ジャケット/上着')
children.children.create(name:'トップス(Tシャツ/カットソー)')
children.children.create(name:'トップス(トレーナー)')
children.children.create(name:'トップス(その他)')
children.children.create(name:'パンツ')
children.children.create(name:'セットアップ')
children.children.create(name:'パジャマ')
children.children.create(name:'フォーマル/ドレス')
children.children.create(name:'和服')
children.children.create(name:'浴衣')
children.children.create(name:'甚平')
children.children.create(name:'水着')
children.children.create(name:'その他')
children = category.children.create(name:'キッズ服(男女兼用) 100cm~')
children.children.create(name:'コート')
children.children.create(name:'ジャケット/上着')
children.children.create(name:'トップス(Tシャツ/カットソー)')
children.children.create(name:'トップス(トレーナー)')
children.children.create(name:'トップス(その他)')
children.children.create(name:'ボトムス')
children.children.create(name:'パジャマ')
children.children.create(name:'その他')
children = category.children.create(name:'キッズ靴')
children.children.create(name:'スニーカー')
children.children.create(name:'サンダル')
children.children.create(name:'ブーツ')
children.children.create(name:'長靴')
children.children.create(name:'その他')
children = category.children.create(name:'子ども用ファッション小物')
children.children.create(name:'靴下/スパッツ')
children.children.create(name:'帽子')
children.children.create(name:'エプロン')
children.children.create(name:'サスペンダー')
children.children.create(name:'タイツ')
children.children.create(name:'ハンカチ')
children.children.create(name:'バンダナ')
children.children.create(name:'ベルト')
children.children.create(name:'マフラー')
children.children.create(name:'傘')
children.children.create(name:'手袋')
children.children.create(name:'スタイ')
children.children.create(name:'バッグ')
children.children.create(name:'その他')
children = category.children.create(name:'おむつ/トイレ/バス')
children.children.create(name:'おむつ用品')
children.children.create(name:'おまる/補助便座')
children.children.create(name:'トレーニングパンツ')
children.children.create(name:'ベビーバス')
children.children.create(name:'お風呂用品')
children.children.create(name:'その他')
children = category.children.create(name:'外出/移動用品')
children.children.create(name:'ベビーカー')
children.children.create(name:'抱っこひも/スリング')
children.children.create(name:'チャイルドシート')
children.children.create(name:'その他')
children = category.children.create(name:'授乳/食事')
children.children.create(name:'ミルク')
children.children.create(name:'ベビーフード')
children.children.create(name:'ベビー用食器')
children.children.create(name:'その他')
children = category.children.create(name:'ベビー家具/寝具/室内用品')
children.children.create(name:'ベッド')
children.children.create(name:'布団/毛布')
children.children.create(name:'イス')
children.children.create(name:'たんす')
children.children.create(name:'その他')
children = category.children.create(name:'おもちゃ')
children.children.create(name:'おふろのおもちゃ')
children.children.create(name:'がらがら')
children.children.create(name:'オルゴール')
children.children.create(name:'ベビージム')
children.children.create(name:'手押し車/カタカタ')
children.children.create(name:'知育玩具')
children.children.create(name:'その他')
children = category.children.create(name:'行事/記念品')
children.children.create(name:'お宮参り用品')
children.children.create(name:'お食い初め用品')
children.children.create(name:'アルバム')
children.children.create(name:'手形/足形')
children.children.create(name:'その他')
category = Category.create(name:'インテリア・住まい・小物')
children = category.children.create(name:'キッチン/食器')
children.children.create(name:'食器')
children.children.create(name:'調理器具')
children.children.create(name:'収納/キッチン雑貨')
children.children.create(name:'弁当用品')
children.children.create(name:'カトラリー(スプーン等)')
children.children.create(name:'テーブル用品')
children.children.create(name:'容器')
children.children.create(name:'エプロン')
children.children.create(name:'アルコールグッズ')
children.children.create(name:'浄水機')
children.children.create(name:'その他')
children = category.children.create(name:'ベッド/マットレス')
children.children.create(name:'セミシングルベッド')
children.children.create(name:'シングルベッド')
children.children.create(name:'セミダブルベッド')
children.children.create(name:'ダブルベッド')
children.children.create(name:'ワイドダブルベッド')
children.children.create(name:'クイーンベッド')
children.children.create(name:'キングベッド')
children.children.create(name:'脚付きマットレスベッド')
children.children.create(name:'マットレス')
children.children.create(name:'すのこベッド')
children.children.create(name:'ロフトベッド/システムベッド')
children.children.create(name:'簡易ベッド/折りたたみベッド')
children.children.create(name:'収納付き')
children.children.create(name:'その他')
children = category.children.create(name:'ソファ/ソファベッド')
children.children.create(name:'ソファセット')
children.children.create(name:'シングルソファ')
children.children.create(name:'ラブソファ')
children.children.create(name:'トリプルソファ')
children.children.create(name:'オットマン')
children.children.create(name:'コーナーソファ')
children.children.create(name:'ビーズソファ/クッションソファ')
children.children.create(name:'ローソファ/フロアソファ')
children.children.create(name:'ソファベッド')
children.children.create(name:'応接セット')
children.children.create(name:'ソファカバー')
children.children.create(name:'リクライニングソファ')
children.children.create(name:'その他')
children = category.children.create(name:'椅子/チェア')
children.children.create(name:'一般')
children.children.create(name:'スツール')
children.children.create(name:'ダイニングチェア')
children.children.create(name:'ハイバックチェア')
children.children.create(name:'ロッキングチェア')
children.children.create(name:'座椅子')
children.children.create(name:'折り畳みイス')
children.children.create(name:'デスクチェア')
children.children.create(name:'その他')
children = category.children.create(name:'机/テーブル')
children.children.create(name:'こたつ')
children.children.create(name:'カウンターテーブル')
children.children.create(name:'サイドテーブル')
children.children.create(name:'センターテーブル')
children.children.create(name:'ダイニングテーブル')
children.children.create(name:'座卓/ちゃぶ台')
children.children.create(name:'アウトドア用')
children.children.create(name:'パソコン用')
children.children.create(name:'事務机/学習机')
children.children.create(name:'その他')
children = category.children.create(name:'収納家具')
children.children.create(name:'リビング収納')
children.children.create(name:'キッチン収納')
children.children.create(name:'玄関/屋外収納')
children.children.create(name:'バス/トイレ収納')
children.children.create(name:'本収納')
children.children.create(name:'本/CD/DVD収納')
children.children.create(name:'洋服タンス/押入れ収納')
children.children.create(name:'電話台/ファックス台')
children.children.create(name:'ドレッサー/鏡台')
children.children.create(name:'棚/ラック')
children.children.create(name:'ケース/ボックス')
children.children.create(name:'その他')
children = category.children.create(name:'ラグ/カーペット/マット')
children.children.create(name:'ラグ')
children.children.create(name:'カーペット')
children.children.create(name:'ホットカーペット')
children.children.create(name:'玄関/キッチンマット')
children.children.create(name:'トイレ/バスマット')
children.children.create(name:'その他')
children = category.children.create(name:'カーテン/ブラインド')
children.children.create(name:'カーテン')
children.children.create(name:'ブラインド')
children.children.create(name:'ロールスクリーン')
children.children.create(name:'のれん')
children.children.create(name:'その他')
children = category.children.create(name:'ライト/照明')
children.children.create(name:'蛍光灯/電球')
children.children.create(name:'天井照明')
children.children.create(name:'フロアスタンド')
children.children.create(name:'その他')
children = category.children.create(name:'寝具')
children.children.create(name:'布団/毛布')
children.children.create(name:'枕')
children.children.create(name:'シーツ/カバー')
children.children.create(name:'その他')
children = category.children.create(name:'インテリア小物')
children.children.create(name:'ごみ箱')
children.children.create(name:'ウェルカムボード')
children.children.create(name:'オルゴール')
children.children.create(name:'クッション')
children.children.create(name:'クッションカバー')
children.children.create(name:'スリッパラック')
children.children.create(name:'ティッシュボックス')
children.children.create(name:'バスケット/かご')
children.children.create(name:'フォトフレーム')
children.children.create(name:'マガジンラック')
children.children.create(name:'モビール')
children.children.create(name:'花瓶')
children.children.create(name:'灰皿')
children.children.create(name:'傘立て')
children = category.children.create(name:'季節/年中行事')
children.children.create(name:'正月')
children.children.create(name:'成人式')
children.children.create(name:'バレンタインデー')
children.children.create(name:'ひな祭り')
children.children.create(name:'子どもの日')
children.children.create(name:'母の日')
children.children.create(name:'父の日')
children.children.create(name:'サマーギフト/お中元')
children.children.create(name:'夏/夏休み')
children.children.create(name:'ハロウィン')
children.children.create(name:'敬老の日')
children.children.create(name:'七五三')
children.children.create(name:'お歳暮')
children.children.create(name:'クリスマス')
children.children.create(name:'その他')
category = Category.create(name:'本・音楽・ゲーム')
children = category.children.create(name:'本')
children.children.create(name:'文学/小説')
children.children.create(name:'人文/社会')
children.children.create(name:'ノンフィクション/教養')
children.children.create(name:'地図/旅行ガイド')
children.children.create(name:'ビジネス/経済')
children.children.create(name:'健康/医学')
children.children.create(name:'コンピュータ/IT')
children.children.create(name:'趣味/スポーツ/実用')
children.children.create(name:'住まい/暮らし/子育て')
children.children.create(name:'アート/エンタメ')
children.children.create(name:'洋書')
children.children.create(name:'絵本')
children.children.create(name:'参考書')
children.children.create(name:'その他')
children = category.children.create(name:'漫画')
children.children.create(name:'全巻セット')
children.children.create(name:'少年漫画')
children.children.create(name:'少女漫画')
children.children.create(name:'青年漫画')
children.children.create(name:'女性漫画')
children.children.create(name:'同人誌')
children.children.create(name:'その他')
children = category.children.create(name:'雑誌')
children.children.create(name:'アート/エンタメ/ホビー')
children.children.create(name:'ファッション')
children.children.create(name:'ニュース/総合')
children.children.create(name:'趣味/スポーツ')
children.children.create(name:'その他')
children = category.children.create(name:'CD')
children.children.create(name:'邦楽')
children.children.create(name:'洋楽')
children.children.create(name:'アニメ')
children.children.create(name:'クラシック')
children.children.create(name:'K-POP/アジア')
children.children.create(name:'キッズ/ファミリー')
children.children.create(name:'その他')
children = category.children.create(name:'DVD/ブルーレイ')
children.children.create(name:'外国映画')
children.children.create(name:'日本映画')
children.children.create(name:'アニメ')
children.children.create(name:'TVドラマ')
children.children.create(name:'ミュージック')
children.children.create(name:'お笑い/バラエティ')
children.children.create(name:'スポーツ/フィットネス')
children.children.create(name:'キッズ/ファミリーその他')
children = category.children.create(name:'レコード')
children.children.create(name:'邦楽')
children.children.create(name:'洋楽')
children.children.create(name:'その他')
children = category.children.create(name:'テレビゲーム')
children.children.create(name:'家庭用ゲーム本体')
children.children.create(name:'家庭用ゲームソフト')
children.children.create(name:'携帯用ゲーム本体')
children.children.create(name:'携帯用ゲームソフト')
children.children.create(name:'PCゲーム')
children.children.create(name:'その他')
category = Category.create(name:'おもちゃ・ホビー・グッズ')
children = category.children.create(name:'おもちゃ')
children.children.create(name:'キャラクターグッズ')
children.children.create(name:'ぬいぐるみ')
children.children.create(name:'小物/アクセサリー')
children.children.create(name:'模型/プラモデル')
children.children.create(name:'ミニカー')
children.children.create(name:'トイラジコン')
children.children.create(name:'プラモデル')
children.children.create(name:'ホビーラジコン')
children.children.create(name:'鉄道模型')
children.children.create(name:'その他')
children = category.children.create(name:'タレントグッズ')
children.children.create(name:'アイドル')
children.children.create(name:'ミュージシャン')
children.children.create(name:'タレント/お笑い芸人')
children.children.create(name:'スポーツ選手')
children.children.create(name:'その他')
children = category.children.create(name:'コミック/アニメグッズ')
children.children.create(name:'ストラップ')
children.children.create(name:'キーホルダー')
children.children.create(name:'バッジ')
children.children.create(name:'カード')
children.children.create(name:'クリアファイル')
children.children.create(name:'ポスター')
children.children.create(name:'タオル')
children.children.create(name:'その他')
children = category.children.create(name:'トレーディングカード')
children.children.create(name:'遊戯王')
children.children.create(name:'マジック：ザ・ギャザリング')
children.children.create(name:'ポケモンカードゲーム')
children.children.create(name:'デュエルマスターズ')
children.children.create(name:'バトルスピリッツ')
children.children.create(name:'プリパラ')
children.children.create(name:'アイカツ')
children.children.create(name:'カードファイト!!')
children.children.create(name:'ヴァンガード')
children.children.create(name:'ヴァイスシュヴァルツ')
children.children.create(name:'プロ野球オーナーズリーグ')
children.children.create(name:'ベースボールヒーローズ')
children.children.create(name:'ドラゴンボール')
children.children.create(name:'スリーブ')
children.children.create(name:'その他')
children = category.children.create(name:'フィギュア')
children.children.create(name:'コミック/アニメ')
children.children.create(name:'特撮')
children.children.create(name:'ゲームキャラクター')
children.children.create(name:'SF/ファンタジー/ホラー')
children.children.create(name:'アメコミ')
children.children.create(name:'スポーツ')
children.children.create(name:'ミリタリー')
children.children.create(name:'その他')
children = category.children.create(name:'楽器/器材')
children.children.create(name:'エレキギター')
children.children.create(name:'アコースティックギター')
children.children.create(name:'ベース')
children.children.create(name:'エフェクター')
children.children.create(name:'アンプ')
children.children.create(name:'弦楽器')
children.children.create(name:'管楽器')
children.children.create(name:'鍵盤楽器')
children.children.create(name:'打楽器')
children.children.create(name:'和楽器')
children.children.create(name:'楽譜/スコア')
children.children.create(name:'レコーディング/PA機器')
children.children.create(name:'DJ機器')
children.children.create(name:'DTM/DAW')
children = category.children.create(name:'コレクション')
children.children.create(name:'武具')
children.children.create(name:'使用済切手/官製はがき')
children.children.create(name:'旧貨幣/金貨/銀貨/記念硬貨')
children.children.create(name:'印刷物')
children.children.create(name:'ノベルティグッズ')
children.children.create(name:'その他')
children = category.children.create(name:'ミリタリー')
children.children.create(name:'トイガン')
children.children.create(name:'個人装備')
children.children.create(name:'その他')
children = category.children.create(name:'美術品')
children.children.create(name:'陶芸')
children.children.create(name:'ガラス')
children.children.create(name:'漆芸')
children.children.create(name:'金属工芸')
children.children.create(name:'絵画/タペストリ')
children.children.create(name:'版画')
children.children.create(name:'彫刻/オブジェクト')
children.children.create(name:'書')
children.children.create(name:'写真')
children.children.create(name:'その他')
children = category.children.create(name:'アート用品')
children.children.create(name:'画材')
children.children.create(name:'額縁')
children.children.create(name:'その他')
children = category.children.create(name:'その他')
children.children.create(name:'トランプ/UNO')
children.children.create(name:'カルタ/百人一首')
children.children.create(name:'ダーツ')
children.children.create(name:'ビリヤード')
children.children.create(name:'麻雀')
children.children.create(name:'パズル/ジグソーパズル')
children.children.create(name:'囲碁/将棋')
children.children.create(name:'オセロ/チェス')
children.children.create(name:'人生ゲーム')
children.children.create(name:'野球/サッカーゲーム')
children.children.create(name:'スポーツ')
children.children.create(name:'三輪車/乗り物')
children.children.create(name:'ヨーヨー')
children.children.create(name:'模型製作用品')
category = Category.create(name:'コスメ・香水・美容')
children = category.children.create(name:'ベースメイク')
children.children.create(name:'ファンデーション')
children.children.create(name:'化粧下地')
children.children.create(name:'コントロールカラー')
children.children.create(name:'BBクリーム')
children.children.create(name:'CCクリーム')
children.children.create(name:'コンシーラー')
children.children.create(name:'フェイスパウダー')
children.children.create(name:'トライアルセット/サンプル')
children.children.create(name:'その他')
children = category.children.create(name:'メイクアップ')
children.children.create(name:'アイシャドウ')
children.children.create(name:'口紅')
children.children.create(name:'リップグロス')
children.children.create(name:'リップライナー')
children.children.create(name:'チーク')
children.children.create(name:'フェイスカラー')
children.children.create(name:'マスカラ')
children.children.create(name:'アイライナー')
children.children.create(name:'つけまつげ')
children.children.create(name:'アイブロウペンシル')
children.children.create(name:'パウダーアイブロウ')
children.children.create(name:'眉マスカラ')
children.children.create(name:'トライアルセット/サンプル')
children.children.create(name:'メイク道具/化粧小物')
children = category.children.create(name:'ネイルケア')
children.children.create(name:'ネイルカラー')
children.children.create(name:'カラージェル')
children.children.create(name:'ネイルベースコート/トップコート')
children.children.create(name:'ネイルアート用品')
children.children.create(name:'ネイルパーツ')
children.children.create(name:'ネイルチップ/付け爪')
children.children.create(name:'手入れ用具')
children.children.create(name:'除光液')
children.children.create(name:'その他')
children = category.children.create(name:'香水')
children.children.create(name:'香水(女性用)')
children.children.create(name:'香水(男性用)')
children.children.create(name:'ユニセックス')
children.children.create(name:'ボディミスト')
children.children.create(name:'その他')
children = category.children.create(name:'スキンケア/基礎化粧品')
children.children.create(name:'化粧水/ローション')
children.children.create(name:'乳液/ミルク')
children.children.create(name:'美容液')
children.children.create(name:'フェイスクリーム')
children.children.create(name:'洗顔料')
children.children.create(name:'クレンジング/メイク落とし')
children.children.create(name:'パック/フェイスマスク')
children.children.create(name:'ジェル/ゲル')
children.children.create(name:'ブースター/導入液')
children.children.create(name:'アイケア')
children.children.create(name:'リップケア')
children.children.create(name:'トライアルセット/サンプル')
children.children.create(name:'洗顔グッズ')
children.children.create(name:'その他')
children = category.children.create(name:'ヘアケア')
children.children.create(name:'シャンプー')
children.children.create(name:'トリートメント')
children.children.create(name:'コンディショナー')
children.children.create(name:'リンス')
children.children.create(name:'スタイリング剤')
children.children.create(name:'カラーリング剤')
children.children.create(name:'ブラシ')
children.children.create(name:'その他')
children = category.children.create(name:'ボディケア')
children.children.create(name:'オイル/クリーム')
children.children.create(name:'ハンドクリーム')
children.children.create(name:'ローション')
children.children.create(name:'日焼け止め/サンオイル')
children.children.create(name:'ボディソープ')
children.children.create(name:'入浴剤')
children.children.create(name:'制汗/デオドラント')
children.children.create(name:'フットケア')
children.children.create(name:'その他')
children = category.children.create(name:'オーラルケア')
children.children.create(name:'口臭防止/エチケット用品')
children.children.create(name:'歯ブラシ')
children.children.create(name:'その他')
children = category.children.create(name:'リラクゼーション')
children.children.create(name:'エッセンシャルオイル')
children.children.create(name:'芳香器')
children.children.create(name:'お香/香炉')
children.children.create(name:'キャンドル')
children.children.create(name:'リラクゼーショングッズ')
children.children.create(name:'その他')
children = category.children.create(name:'ダイエット')
children.children.create(name:'ダイエット食品')
children.children.create(name:'エクササイズ用品')
children.children.create(name:'体重計')
children.children.create(name:'体脂肪計')
children.children.create(name:'その他')
children = category.children.create(name:'その他')
children.children.create(name:'健康用品')
children.children.create(name:'看護/介護用品')
children.children.create(name:'救急/衛生用品')
children.children.create(name:'その他')
category = Category.create(name:'家電・スマホ・カメラ')
children = category.children.create(name:'スマートフォン/携帯電話')
children.children.create(name:'スマートフォン本体')
children.children.create(name:'バッテリー/充電器')
children.children.create(name:'携帯電話本体')
children.children.create(name:'PHS本体')
children.children.create(name:'その他')
children = category.children.create(name:'スマホアクセサリー')
children.children.create(name:'Android用ケース')
children.children.create(name:'iPhone用ケース')
children.children.create(name:'カバー')
children.children.create(name:'イヤホンジャック')
children.children.create(name:'ストラップ')
children.children.create(name:'フィルム')
children.children.create(name:'自撮り棒')
children.children.create(name:'その他')
children = category.children.create(name:'PC/タブレット')
children.children.create(name:'タブレット')
children.children.create(name:'ノートPC')
children.children.create(name:'デスクトップ型PC')
children.children.create(name:'ディスプレイ')
children.children.create(name:'電子ブックリーダー')
children.children.create(name:'PC周辺機器')
children.children.create(name:'PCパーツ')
children.children.create(name:'その他')
children = category.children.create(name:'カメラ')
children.children.create(name:'デジタルカメラ')
children.children.create(name:'ビデオカメラ')
children.children.create(name:'レンズ(単焦点)')
children.children.create(name:'レンズ(ズーム)')
children.children.create(name:'フィルムカメラ')
children.children.create(name:'防犯カメラ')
children.children.create(name:'その他')
children = category.children.create(name:'テレビ/映像機器')
children.children.create(name:'テレビ')
children.children.create(name:'プロジェクター')
children.children.create(name:'ブルーレイレコーダー')
children.children.create(name:'DVDレコーダー')
children.children.create(name:'ブルーレイプレーヤー')
children.children.create(name:'DVDプレーヤー')
children.children.create(name:'映像用ケーブル')
children.children.create(name:'その他')
children = category.children.create(name:'オーディオ機器')
children.children.create(name:'ポータブルプレーヤー')
children.children.create(name:'イヤフォン')
children.children.create(name:'ヘッドフォン')
children.children.create(name:'アンプ')
children.children.create(name:'スピーカー')
children.children.create(name:'ケーブル/シールド')
children.children.create(name:'ラジオ')
children.children.create(name:'その他')
children = category.children.create(name:'美容/健康')
children.children.create(name:'ヘアドライヤー')
children.children.create(name:'ヘアアイロン')
children.children.create(name:'美容機器')
children.children.create(name:'電気シェーバー')
children.children.create(name:'電動歯ブラシ')
children.children.create(name:'その他')
children = category.children.create(name:'冷暖房/空調')
children.children.create(name:'エアコン')
children.children.create(name:'空気清浄器')
children.children.create(name:'加湿器')
children.children.create(name:'扇風機')
children.children.create(name:'除湿機')
children.children.create(name:'ファンヒーター')
children.children.create(name:'電気ヒーター')
children.children.create(name:'オイルヒーター')
children.children.create(name:'ストーブ')
children.children.create(name:'ホットカーペット')
children.children.create(name:'こたつ')
children.children.create(name:'電気毛布')
children.children.create(name:'その他')
children = category.children.create(name:'生活家電')
children.children.create(name:'冷蔵庫')
children.children.create(name:'洗濯機')
children.children.create(name:'炊飯器')
children.children.create(name:'電子レンジ/オーブン')
children.children.create(name:'調理機器')
children.children.create(name:'アイロン')
children.children.create(name:'掃除機')
children.children.create(name:'エスプレッソマシン')
children.children.create(name:'コーヒーメーカー')
children.children.create(name:'衣類乾燥機')
children.children.create(name:'その他')
children.children.create(name:'その他')
children.children.create(name:'その他')
category = Category.create(name:'スポーツ・レジャー')
children = category.children.create(name:'ゴルフ')
children.children.create(name:'クラブ')
children.children.create(name:'ウエア(男性用)')
children.children.create(name:'ウエア(女性用)')
children.children.create(name:'バッグ')
children.children.create(name:'シューズ(男性用)')
children.children.create(name:'シューズ(女性用)')
children.children.create(name:'アクセサリー')
children.children.create(name:'その他')
children = category.children.create(name:'フィッシング')
children.children.create(name:'ロッド')
children.children.create(name:'リール')
children.children.create(name:'ルアー用品')
children.children.create(name:'ウエア')
children.children.create(name:'釣り糸/ライン')
children.children.create(name:'その他')
children = category.children.create(name:'自転車')
children.children.create(name:'自転車本体')
children.children.create(name:'ウエア')
children.children.create(name:'パーツ')
children.children.create(name:'アクセサリー')
children.children.create(name:'バッグ')
children.children.create(name:'工具/メンテナンス')
children.children.create(name:'その他')
children = category.children.create(name:'トレーニング/エクササイズ')
children.children.create(name:'ランニング')
children.children.create(name:'ウォーキング')
children.children.create(name:'ヨガ')
children.children.create(name:'トレーニング用品')
children.children.create(name:'その他')
children = category.children.create(name:'野球')
children.children.create(name:'ウェア')
children.children.create(name:'シューズ')
children.children.create(name:'グローブ')
children.children.create(name:'バット')
children.children.create(name:'アクセサリー')
children.children.create(name:'防具')
children.children.create(name:'練習機器')
children.children.create(name:'記念グッズ')
children.children.create(name:'応援グッズ')
children.children.create(name:'その他')
children = category.children.create(name:'サッカー/フットサル')
children.children.create(name:'ウェア')
children.children.create(name:'シューズ')
children.children.create(name:'ボール')
children.children.create(name:'アクセサリー')
children.children.create(name:'記念グッズ')
children.children.create(name:'応援グッズ')
children.children.create(name:'その他')
children = category.children.create(name:'テニス')
children.children.create(name:'ラケット(硬式用)')
children.children.create(name:'ラケット(軟式用)')
children.children.create(name:'ウェア')
children.children.create(name:'シューズ')
children.children.create(name:'ボール')
children.children.create(name:'アクセサリー')
children.children.create(name:'記念グッズ')
children.children.create(name:'応援グッズ')
children.children.create(name:'その他')
children = category.children.create(name:'スノーボード')
children.children.create(name:'ボード')
children.children.create(name:'バインディング')
children.children.create(name:'ブーツ(男性用)')
children.children.create(name:'ブーツ(女性用)')
children.children.create(name:'ブーツ(子ども用)')
children.children.create(name:'ウエア/装備(男性用)')
children.children.create(name:'ウエア/装備(女性用)')
children.children.create(name:'ウエア/装備(子ども用)')
children.children.create(name:'アクセサリー')
children.children.create(name:'バッグ')
children.children.create(name:'その他')
children = category.children.create(name:'スキー')
children.children.create(name:'板')
children.children.create(name:'ブーツ(男性用)')
children.children.create(name:'ブーツ(女性用)')
children.children.create(name:'ブーツ(子ども用)')
children.children.create(name:'ビンディング')
children.children.create(name:'ウエア(男性用)')
children.children.create(name:'ウエア(女性用)')
children.children.create(name:'ウエア(子ども用)')
children.children.create(name:'ストック')
children.children.create(name:'その他')
children.children.create(name:'その他')
children = category.children.create(name:'スポーツ')
children.children.create(name:'ダンス/バレエ')
children.children.create(name:'サーフィン')
children.children.create(name:'バスケットボール')
children.children.create(name:'バドミントン')
children.children.create(name:'バレーボール')
children.children.create(name:'スケートボード')
children.children.create(name:'陸上競技')
children.children.create(name:'ラグビー')
children.children.create(name:'アメリカンフットボール')
children.children.create(name:'ボクシング')
children.children.create(name:'ボウリング')
children.children.create(name:'その他')
children = category.children.create(name:'アウトドア')
children.children.create(name:'テント/タープ')
children.children.create(name:'ライト/ランタン')
children.children.create(name:'寝袋/寝具')
children.children.create(name:'テーブル/チェア')
children.children.create(name:'ストーブ/コンロ')
children.children.create(name:'調理器具')
children.children.create(name:'食器')
children.children.create(name:'登山用品')
children.children.create(name:'その他')
children = category.children.create(name:'その他')
children.children.create(name:'旅行用品')
children.children.create(name:'その他')
category = Category.create(name:'ハンドメイド')
children = category.children.create(name:'アクセサリー(女性用)')
children.children.create(name:'ピアス')
children.children.create(name:'イヤリング')
children.children.create(name:'ネックレス')
children.children.create(name:'ブレスレット')
children.children.create(name:'リング')
children.children.create(name:'チャーム')
children.children.create(name:'ヘアゴム')
children.children.create(name:'アンクレット')
children.children.create(name:'その他')
children = category.children.create(name:'ファッション/小物')
children.children.create(name:'バッグ(女性用)')
children.children.create(name:'バッグ(男性用)')
children.children.create(name:'財布(女性用)')
children.children.create(name:'財布(男性用)')
children.children.create(name:'ファッション雑貨')
children.children.create(name:'その他')
children = category.children.create(name:'アクセサリー/時計')
children.children.create(name:'アクセサリー(男性用)')
children.children.create(name:'時計(女性用)')
children.children.create(name:'時計(男性用)')
children.children.create(name:'その他')
children = category.children.create(name:'日用品/インテリア')
children.children.create(name:'キッチン用品')
children.children.create(name:'家具')
children.children.create(name:'文房具')
children.children.create(name:'アート/写真')
children.children.create(name:'アロマ/キャンドル')
children.children.create(name:'フラワー/ガーデン')
children.children.create(name:'その他')
children = category.children.create(name:'趣味/おもちゃ')
children.children.create(name:'クラフト/布製品')
children.children.create(name:'おもちゃ/人形')
children.children.create(name:'その他')
children = category.children.create(name:'キッズ/ベビー')
children.children.create(name:'ファッション雑貨')
children.children.create(name:'スタイ/よだれかけ')
children.children.create(name:'外出用品')
children.children.create(name:'ネームタグ')
children.children.create(name:'その他')
children = category.children.create(name:'素材/材料')
children.children.create(name:'各種パーツ')
children.children.create(name:'生地/糸')
children.children.create(name:'型紙/パターン')
children.children.create(name:'その他')
children = category.children.create(name:'二次創作物')
children.children.create(name:'Ingress')
children.children.create(name:'クリエイターズ宇宙兄弟')
children.children.create(name:'その他')
category = Category.create(name:'チケット')
children = category.children.create(name:'音楽')
children.children.create(name:'男性アイドル')
children.children.create(name:'女性アイドル')
children.children.create(name:'韓流')
children.children.create(name:'国内アーティスト')
children.children.create(name:'海外アーティスト')
children.children.create(name:'音楽フェス')
children.children.create(name:'声優/アニメ')
children.children.create(name:'その他')
children = category.children.create(name:'スポーツ')
children.children.create(name:'サッカー')
children.children.create(name:'野球')
children.children.create(name:'テニス')
children.children.create(name:'格闘技/プロレス')
children.children.create(name:'相撲/武道')
children.children.create(name:'ゴルフ')
children.children.create(name:'バレーボール')
children.children.create(name:'バスケットボール')
children.children.create(name:'モータースポーツ')
children.children.create(name:'ウィンタースポーツ')
children.children.create(name:'その他')
children = category.children.create(name:'演劇/芸能')
children.children.create(name:'ミュージカル')
children.children.create(name:'演劇')
children.children.create(name:'伝統芸能')
children.children.create(name:'落語')
children.children.create(name:'お笑い')
children.children.create(name:'オペラ')
children.children.create(name:'サーカス')
children.children.create(name:'バレエ')
children.children.create(name:'その他')
children = category.children.create(name:'イベント')
children.children.create(name:'声優/アニメ')
children.children.create(name:'キッズ/ファミリー')
children.children.create(name:'トークショー/講演会')
children.children.create(name:'その他')
children = category.children.create(name:'映画')
children.children.create(name:'邦画')
children.children.create(name:'洋画')
children.children.create(name:'その他')
children = category.children.create(name:'施設利用券')
children.children.create(name:'遊園地/テーマパーク')
children.children.create(name:'美術館/博物館')
children.children.create(name:'スキー場')
children.children.create(name:'ゴルフ場')
children.children.create(name:'フィットネスクラブ')
children.children.create(name:'プール')
children.children.create(name:'ボウリング場')
children.children.create(name:'水族館')
children.children.create(name:'動物園')
children.children.create(name:'その他')
children = category.children.create(name:'優待券/割引券')
children.children.create(name:'ショッピング')
children.children.create(name:'レストラン/食事券')
children.children.create(name:'フード/ドリンク券')
children.children.create(name:'宿泊券')
children.children.create(name:'その他')
children.children.create(name:'その他')
category = Category.create(name:'自動車・オートバイ')
children = category.children.create(name:'自動車本体')
children.children.create(name:'国内自動車本体')
children.children.create(name:'外国自動車本体')
children = category.children.create(name:'自動車タイヤ/ホイール')
children.children.create(name:'タイヤ/ホイールセット')
children.children.create(name:'タイヤ')
children.children.create(name:'ホイール')
children.children.create(name:'その他')
children = category.children.create(name:'自動車パーツ')
children.children.create(name:'サスペンション')
children.children.create(name:'ブレーキ')
children.children.create(name:'外装、エアロパーツ')
children.children.create(name:'ライト')
children.children.create(name:'内装品、シート')
children.children.create(name:'ステアリング')
children.children.create(name:'マフラー・排気系')
children.children.create(name:'エンジン、過給器、冷却装置')
children.children.create(name:'クラッチ、ミッション、駆動系')
children.children.create(name:'電装品')
children.children.create(name:'補強パーツ')
children.children.create(name:'汎用パーツ')
children.children.create(name:'外国自動車用パーツ')
children.children.create(name:'その他')
children = category.children.create(name:'自動車アクセサリー')
children.children.create(name:'車内アクセサリー')
children.children.create(name:'カーナビ')
children.children.create(name:'カーオーディオ')
children.children.create(name:'車外アクセサリー')
children.children.create(name:'メンテナンス用品')
children.children.create(name:'チャイルドシート')
children.children.create(name:'ドライブレコーダー')
children.children.create(name:'レーダー探知機')
children.children.create(name:'カタログ/マニュアル')
children.children.create(name:'セキュリティ')
children.children.create(name:'その他')
children = category.children.create(name:'オートバイ車体')
children = category.children.create(name:'オートバイパーツ')
children.children.create(name:'タイヤ')
children.children.create(name:'マフラー')
children.children.create(name:'エンジン、冷却装置')
children.children.create(name:'カウル、フェンダー、外装')
children.children.create(name:'サスペンション')
children.children.create(name:'ホイール')
children.children.create(name:'シート')
children.children.create(name:'ブレーキ')
children.children.create(name:'タンク')
children.children.create(name:'ライト、ウィンカー')
children.children.create(name:'チェーン、スプロケット、駆動系')
children.children.create(name:'メーター')
children.children.create(name:'電装系')
children.children.create(name:'ミラー')
children = category.children.create(name:'オートバイアクセサリー')
children.children.create(name:'ヘルメット/シールド')
children.children.create(name:'バイクウエア/装備')
children.children.create(name:'アクセサリー')
children.children.create(name:'メンテナンス')
children.children.create(name:'カタログ/マニュアル')
children.children.create(name:'その他')
category = Category.create(name:'その他')
children = category.children.create(name:'まとめ売り')
children = category.children.create(name:'ペット用品')
children.children.create(name:'ペットフード')
children.children.create(name:'犬用品')
children.children.create(name:'猫用品')
children.children.create(name:'魚用品/水草')
children.children.create(name:'小動物用品')
children.children.create(name:'爬虫類/両生類用品')
children.children.create(name:'かご/おり')
children.children.create(name:'鳥用品')
children.children.create(name:'虫類用品')
children.children.create(name:'その他')
children = category.children.create(name:'食品')
children.children.create(name:'菓子')
children.children.create(name:'米')
children.children.create(name:'野菜')
children.children.create(name:'果物')
children.children.create(name:'調味料')
children.children.create(name:'魚介類(加工食品)')
children.children.create(name:'肉類(加工食品)')
children.children.create(name:'その他加工食品')
children.children.create(name:'その他')
children = category.children.create(name:'飲料/酒')
children.children.create(name:'コーヒー')
children.children.create(name:'ソフトドリンク')
children.children.create(name:'ミネラルウォーター')
children.children.create(name:'茶')
children.children.create(name:'ウイスキー')
children.children.create(name:'ワイン')
children.children.create(name:'ブランデー')
children.children.create(name:'焼酎')
children.children.create(name:'日本酒')
children.children.create(name:'ビール、発泡酒')
children.children.create(name:'その他')
children = category.children.create(name:'日用品/生活雑貨/旅行')
children.children.create(name:'タオル/バス用品')
children.children.create(name:'日用品/生活雑貨')
children.children.create(name:'洗剤/柔軟剤')
children.children.create(name:'旅行用品')
children.children.create(name:'防災関連グッズ')
children.children.create(name:'その他')
children = category.children.create(name:'アンティーク/コレクション')
children.children.create(name:'雑貨')
children.children.create(name:'工芸品')
children.children.create(name:'家具')
children.children.create(name:'印刷物')
children.children.create(name:'その他')
children = category.children.create(name:'文房具/事務用品')
children.children.create(name:'筆記具')
children.children.create(name:'ノート/メモ帳')
children.children.create(name:'テープ/マスキングテープ')
children.children.create(name:'カレンダー/スケジュール')
children.children.create(name:'アルバム/スクラップ')
children.children.create(name:'ファイル/バインダー')
children.children.create(name:'はさみ/カッター')
children.children.create(name:'カードホルダー/名刺管理')
children.children.create(name:'のり/ホッチキス')
children.children.create(name:'その他')
children = category.children.create(name:'事務/店舗用品')
children.children.create(name:'オフィス用品一般')
children.children.create(name:'オフィス家具')
children.children.create(name:'店舗用品')
children.children.create(name:'OA機器')
children.children.create(name:'ラッピング/包装')
children.children.create(name:'その他')
children = category.children.create(name:'その他')

Size.create!(
  [
    {
      id: 1,
      size: 'XXS以下',
    },
    {
      id: 2,
      size: 'XS(SS)',
    },
    {
      id: 3,
      size: 'S',
    },
    {
      id: 4,
      size: 'M',
    },
    {
      id: 5,
      size: 'L',
    },
    {
      id: 6,
      size: 'XL(LL)',
    },
    {
      id: 7,
      size: '2XL(3L)',
    },
    {
      id: 8,
      size: '3XL(4L)',
    },
    {
      id: 9,
      size: '4XL(5L)以上',
    },
    {
      id: 10,
      size: 'FREE SIZE',
    },
  ]
)
Brand.create!(
  [
    {
      id: 1,
      name: 'NIKE',
    }
  ]
)
CommodityCondition.create!(
  [
    {
      id: 1,
      condition: '新品、未使用',
    },
    {
      id: 2,
      condition: '未使用に近い',
    },
    {
      id: 3,
      condition: '目立った傷や汚れなし',
    },
    {
      id: 4,
      condition: 'やや傷や汚れあり',
    },
    {
      id: 5,
      condition: '傷や汚れあり',
    },
    {
      id: 6,
      condition: '全体的に状態が悪い',
    }
  ]
)
ShippingCharge.create!(
  [
    {
      id: 1,
      method: '送料込み(出品者負担)',
    },
    {
      id: 2,
      method: '着払い(購入者負担)',
    }
  ]
)
DeliveryMethod.create!(
  [
    {
      id: 1,
      name: '未定',
    },
    {
      id: 2,
      name: 'らくらくメルカリ便',
    },
    {
      id: 3,
      name: 'ゆうメール',
    },
    {
      id: 4,
      name: 'レターパック',
    },
    {
      id: 5,
      name: '普通郵便(定形、定形外)',
    },
    {
      id: 6,
      name: 'クロネコヤマト',
    },
    {
      id: 7,
      name: 'ゆうパック',
    },
    {
      id: 8,
      name: 'クリックポスト',
    },
    {
      id: 9,
      name: 'ゆうパケット',
    }
  ]
)
DaysBeforeShipment.create!(
  [
    {
      id: 1,
      days: '1〜2日で発送',
    },
    {
      id: 2,
      days: '2〜3日で発送',
    },
    {
      id: 3,
      days: '4〜7日で発送',
    },
  ]
)
User.create!(
  [
    {
      id: 1,
      family_name_kanji: '山田',
      first_name_kanji: '太郎',
      family_name_cana: 'ヤマダ',
      first_name_cana: 'タロウ',
      year: '1999',
      month: '11',
      day: '11',
      image: '',
      nickname: 'ヤマダ',
      explain: 'テストです',
      email: 'i@i',
      password: 'r1108y1108o'
    }
  ]
)
Condition.create!(
  [
    {
      id: 1,
      condition: '出品中',
    },
    {
      id: 2,
      condition: '取引中',
    },
    {
      id: 3,
      condition: '売却済み',
    }
  ]
)